version: '3.8'

services:
  app:
    container_name: cms-app
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8051:3000"
    environment:
      - DATABASE_URL=mysql://root:Demandify%40766@20.244.10.206:3306/cms
      - NEXTAUTH_URL=http://20.244.10.206:8051
      - NEXTAUTH_SECRET=your-production-secret-key-change-this-to-something-secure
    networks:
      - cms-network

networks:
  cms-network:
    driver: bridge
